services:
  django:
    env_file: &env_file ./src/.env
    build: &build
      context: .
      target: dev
    working_dir: &working_dir /opt/django    
    command:
      - gunicorn
      - config.wsgi
      - --bind
      - 0.0.0.0:8000
      - --log-level
      - info
    ports:
      - "8000:8000"    
    volumes:      
      - ./src:/opt/django
    depends_on: &depends_on
      - redis

  celery:
    env_file: *env_file
    build: *build
    working_dir: *working_dir    
    command:
      - uv
      - run
      - celery
      - --app=config
      - worker
      - --task-events
      - --concurrency=1
      - --loglevel=DEBUG    
    depends_on: *depends_on

  redis:
    image: redis:alpine
